#!/bin/bash
# VPS Installer
# Script by Juan

read -p "Enter User:" user
read -p "Enter Password:" pass
echo \ '
users : EAP "passx"' >> /etc/ipsec.secrets
sed -i "s|users|$user|g" /etc/ipsec.secrets
sed -i "s|passx|$pass|g" /etc/ipsec.secrets
systemctl restart ipsec
echo -e "SAVE THIS FILE AS PEM"
cat /etc/ipsec.d/cacerts/ca-cert.pem
