#!/bin/bash
# VPS Installer
# Script by Juan
export DEBIAN_FRONTEND=noninteractive
IPADDR="$(curl -4skL http://ipinfo.io/ip)"
apt update
apt-get install strongswan libcharon-extra-plugins libstrongswan-extra-plugins strongswan-pki -y
mkdir -p ~/pki/{cacerts,certs,private}
chmod 700 ~/pki
ipsec pki --gen --type rsa --size 4096 --outform pem > ~/pki/private/ca-key.pem
ipsec pki --self --ca --lifetime 3650 --in ~/pki/private/ca-key.pem \
    --type rsa --dn "CN=freenet cafe" --outform pem > ~/pki/cacerts/ca-cert.pem
ipsec pki --gen --type rsa --size 4096 --outform pem > ~/pki/private/server-key.pem

ipsec pki --pub --in ~/pki/private/server-key.pem --type rsa \
    | ipsec pki --issue --lifetime 1825 \
        --cacert ~/pki/cacerts/ca-cert.pem \
        --cakey ~/pki/private/ca-key.pem \
        --dn "CN=$IPADDR" --san "$IPADDR" \
        --flag serverAuth --flag ikeIntermediate --outform pem \
    >  ~/pki/certs/server-cert.pem
sudo cp -r ~/pki/* /etc/ipsec.d/
sudo cp -r ~/pki/* /etc/ipsec.d/
wget -q -O /etc/ipsec.conf https://github.com/yakult13/IKEV2/raw/main/ipsec.conf
sed -i "s|ADDE|$IPADDR|g" /etc/ipsec.conf
echo ': RSA "server-key.pem"' >> /etc/ipsec.secrets
echo ': PSK "freenetcafe"' >> /etc/ipsec.secrets
sudo systemctl restart strongswan
sudo ufw allow OpenSSH
sudo ufw enable
sudo ufw allow 500,4500/udp
wget -q -O c https://github.com/yakult13/IKEV2/raw/main/before.rules
chmod +x /etc/ufw/before.rules
wget -q -O /etc/ufw/sysctl.conf https://github.com/yakult13/IKEV2/raw/main/sysctl.conf
sudo ufw disable
sudo ufw enable
